export enum QueryKey {
  FETCH_ANIME = "FETCH_ANIME",
  FETCH_ANIME_LIST = "FETCH_ANIME_LIST",
  FETCH_MY_SCRAPS = "FETCH_MY_SCRAPS",
  FETCH_MY_REVIEW = "FETCH_MY_REVIEW",
  FETCH_REVIEWS_BY_ANIME = "FETCH_REVIEWS_BY_ANIME",
}
