export enum QueryKey {
  FETCH_ANIME = "FETCH_ANIME",
  FETCH_ANIME_LIST = "FETCH_ANIME_LIST",
  FETCH_AUTH_ANIME_LIST = "FETCH_AUTH_ANIME_LIST",
  FETCH_MY_SCRAPS = "FETCH_MY_SCRAPS",
  FETCH_GET_MY_REVIEW = "FETCH_GET_MY_REVIEW",
  FETCH_REVIEWS_BY_ANIME = "FETCH_REVIEWS_BY_ANIME",
  FETCH_GET_SERIES_LIST = "FETCH_GET_SERIES_LIST",
  FETCH_GET_USER_INFO = "FETCH_GET_USER_INFO",
  FETCH_GET_CREW_LIST = "FETCH_GET_CREW_LISt",
  FETCH_GET_SERIES = "FETCH_GET_SERIES",
}
